version: "3.9"

services:
  database:
    image: mysql:8.0
    container_name: t4y-database
    env_file:
      - ./backend/.env
    ports:
    - 3306:3306

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: t4y-backend
    volumes:
      - ./backend:/backend
    restart: on-failure
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - DB_HOST=t4y-database
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    command: sh -c "/wait &  python manage.py makemigrations common
      && python manage.py migrate common
      && python manage.py makemigrations image
      && python manage.py migrate image
      && python manage.py runserver 0.0.0.0:8000"
    tty: true
#    env_file:
#      - ./backend/.env
    # environment:
    #   - MYSQL_ROOT_PASSWORD=rootpassword
    #   - MYSQL_DATABASE=${mydatabase}
    #   - MYSQL_USER=myuser
    #   - MYSQL_PASSWORD=mypassword

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: t4y-frontend
  #   ports:
  #     - "3000:3000" # 포트 매핑 설정
  #   volumes:
  #     - ./frontend:/frontend
