# Generated by Django 4.2.3 on 2023-07-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ai_model',
        ),
    ]
