# Generated by Django 4.1 on 2023-07-13 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ai_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_url_1', models.URLField()),
                ('result_url_2', models.URLField()),
                ('result_url_3', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('image_origin_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='image.image_origin')),
            ],
        ),
    ]
