# Generated by Django 4.1 on 2023-07-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_ai_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ai_model',
        ),
    ]
