# Generated by Django 4.2.2 on 2023-07-21 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('img_origin_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='image.image_origin')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image_chosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_1', models.URLField()),
                ('url_2', models.URLField()),
                ('url_3', models.URLField()),
                ('url_4', models.URLField()),
                ('model_chosen_1', models.URLField()),
                ('model_chosen_2', models.URLField()),
                ('model_chosen_3', models.URLField()),
                ('model_chosen_4', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('img_origin_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='image.image_origin')),
            ],
        ),
    ]
