global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 2m

# 프로메테우스 연결
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# 백엔드 서버와 연결
  - job_name: '2023sb-team-j-backend'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8000' ]
    metrics_path: '/admin/'
