on:
  push:
    branches:
      - 'frontend/*/*'

jobs:
  deploy:
    name: 'Build & Deploy'
    runs-on: ubuntu-latest

    steps:
#      "docker://{image}:{tag}" docker://{host}/{image}:{tag}
      - uses: "docker://frontend"
      - name: Use Node.js
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npm install
        if: ${{ always() }}
      - run: npm run tsc
        if: ${{ always() }}
      - run: npm run lint
        if: ${{ always() }}
      - run: npm run build
        if: ${{ always() }}