name: front_deploy

on:
  push:
    branches:
      - 'frontend/*/*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
#      "docker://{image}:{tag}" docker://{host}/{image}:{tag}
      - uses: "docker://frontend"

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14-alpine

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci


      - name: Send slack when failed
        if: ${{ failure() }}
        uses: ./.github/actions/slack-notify
        with:
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}

      - name: Send slack if completed
        if: ${{ success() }}
        uses: ./.github/actions/slack-notify
        with:
          status: success
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}